leanprover-community/lean

library/init/meta/smt/interactive.lean, library/init/meta/tactic.lean, src/frontends/lean/tactic_notation.cpp, src/library/constants.cpp, src/library/constants.h, tests/lean/interactive/my_tac_class.lean, tests/lean/interactive/rb_map_ts.lean, tests/lean/run/my_tac_class.lean
In core lean in order to define a custom interaction monad (i.e. the data required to be able to use `begin ... end` and `by ...` blocks), you need to define several functions (as detailed in the header of [src/frontends/lean/tactic_notation.cpp](https://github.com/leanprover-community/lean/blob/master/src/frontends/lean/tactic_notation.cpp)). Of note are the lines:
````
7) There is a definition Tac.execute (tac : Tac unit) : tactic unit
8) There is a definition Tac.execute_with (cfg : config) (tac : Tac unit) : tactic unit
````
We generalise these pair of functions into an instance which can be made available for any custom `Tac` you would like, without hard-coding functions with these specific hardcoded names (which cannot then be overridden, for example). We instead just offload this …
=> feat(tactic/interactive): generalize custom tactic monads in `begin ... end` blocks

src/frontends/lean/parser.cpp, src/kernel/expr.cpp, src/library/discr_tree.cpp, src/library/inductive_compiler/basic.cpp, src/library/inductive_compiler/util.cpp, src/library/replace_visitor.cpp, src/util/rb_tree.h, src/util/small_object_allocator.h, src/util/trie.h
Newer C++ compilers include a compiler warning for when an argument is given move semantics (the `&&` thing) but is copied because `std::move` is not used.
I added std::move to all of the places that this warning came up because I got sick of seeing them in my build.
In  `src/library/inductive_compiler/basic.cpp`, `add_basic_inductive_decl_fn`'s `m_implicit_infer_map` field caused an error because it is implicitly cast to a reference. When I look at `name_map<T>`, it is already a pointer so it seems to my naive eyes that the best way to remove this warning is for the `m_implicit_infer_map` to be a value instead of a reference.
I made the warning go away and all the tests pass so it works in that sense.
I am least sure about this change. In ` src/util/small_object_allocator.h`, I get …
=> Remove compiler warnings on newer gccs

.travis.yml, script/ci_emscripten_docker.sh, src/shell/emscripten.h
Emscripten's filesystem contains `/home` by default and so attempting to create the directory again before mounting resulted in an error. I didn't see this on my local setup since macOS's home is under `/User`. I addressed this by including a test for Emscripten's default directories in the relevant code.
Another fix is to the travis scripts. We now create the `build` directory outside of docker to prevent permissions issues later on when trying to write the `lean-(version)-browser.zip` file.
Hopefully this fixes the issues keeping the browser build from being uploaded to the `lean-nightly` release!
=> fix(src/shell/emscripten.h): Emscripten FS issue

library/init/meta/attribute.lean, library/init/meta/expr.lean, library/init/meta/tactic.lean, src/library/documentation.cpp
The commit message for fb74ebb basically covers the before and after,
Not all doc strings were being checked for balance,
The first commit fixes the unbalanced doc strings that were in core
before the patch, since now those doc strings will cause an error.
Further some doc strings, containing an "info string", (e.g. language),
were in some cases being mangled, when trying to add the default lean language.
because it only recognized doc strings immediately followed by white space as the start
of a code block.
=> Fix some cases when adding lean language to the start of a code block

library/init/meta/level.lean, src/library/vm/vm_level.cpp, tests/lean/level_instantiate.lean, tests/lean/level_instantiate.lean.expected.out
`level.instantiate` should return a single level rather than a list of levels. I don't think this builtin is used in mathlib, I tested it on `leanprover/mathlib` and nothing broke.
=> fix(level): give level.instantiate correct type

.travis.yml
Seeing if `kill -9` will fix the issue mentioned [here](https://github.com/leanprover-community/lean/pull/67#issuecomment-536062723).
**Edit**: The real fix was using `pkill` to more robustly find the `sleep` process.
=> fix(.travis.yml): fix emscripten build in travis

src/library/documentation.cpp, tests/lean/doc_string_ctr.lean.expected.out, tests/lean/doc_strings.lean, tests/lean/doc_strings.lean.expected.out
This PR makes documentation output work when used via `--doc=mydoc.md`. Fixes #51. It's something that I hacked together really quickly, so most likely not the prettiest solution. The Lean build system is a fairly complicated multithreaded thing, and I don't fully understand the implications of the changes here. I would appreciate it if someone more knowledgeable in the Lean module/environment/extension system could take a look - I will leave a couple of comments at places I'm not sure about.
It works a little *too* well, in that the documentation includes not only the current module's declarations, but also all transitively imported declarations - the standard library and maybe mathlib. Given this input:
```lean
/-! Module doc 1 -/
/-! Module doc 2 -/
/-- Foo is an inductive type. -/ …
```
=> feat(olean): store module documentation in .olean files

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, README.md, doc/export_format.md, doc/faq.md, doc/make/index.md
[skip ci]
fixes #73
Update issue hyperlinks in documentation files.
It might be worth deleting the 'roadmap' section of the readme but that can be done elsewhere.
=> fix(73): Update github issue hyperlinks

doc/changes.md, library/init/meta/tactic.lean, src/frontends/lean/parser.cpp, src/library/documentation.cpp, src/library/documentation.h, src/library/module.cpp, src/library/module.h, src/library/tactic/tactic_state.cpp, src/shell/leandoc.cpp, tests/lean/doc_strings.lean, tests/lean/doc_strings.lean.expected.out
Changes the semantics of `module_doc_strings` to contain a list of `(some filename, top-level-docstring)` pairs, plus a `(none, top-level-docstring)` for the current module. If a single module contains multiple top-level docstrings, they're concatenated with newlines (but I could make it a list like before if people want). Declaration docstrings are no longer present in the output, since they're accessible via `doc_string` anyway.
CC @robertylewis
=> feat(tactic): make docstrings of imported modules accessible

src/library/check.cpp, src/library/check.h, src/library/tactic/tactic_state.cpp, tests/lean/run/type_check_mvar.lean
The `tactic.type_check` function has a slightly surprising behavior: it can assign metavariables during type-checking.  For example the term `@eq.{?l_1} ?m_1 nat.zero nat.zero` type-checks according to `tactic.type_check` (where `?l_1` and `?m_1` are unassigned metavariables).  The tactic state is also not updated to reflect the metavariables assigned during type-checking.
This PR changes the behavior of `tactic.type_check` to *not* assign metavariables.
=> fix(library/check): do not assign metavariables in tactic.type_check

.travis.yml
Previously, during travis jobs, the emscripten build was only stored in a ZIP under `build/` for builds on `master`. This change causes the ZIP file to be generated for all travis jobs, in particular, for release builds.
=> fix(build): generate emscripten zip for releases

src/frontends/lean/pp.cpp, src/frontends/lean/pp.h, src/library/local_context.cpp, src/library/pp_options.cpp, src/library/pp_options.h, src/library/type_context.cpp, tests/lean/1836.lean.expected.out, tests/lean/add_defn_eqns.lean.expected.out, tests/lean/pp_generalized_field_notation.lean, tests/lean/pp_generalized_field_notation.lean.expected.out, tests/lean/pp_links.lean, tests/lean/pp_links.lean.expected.out, tests/lean/proj_notation.lean.expected.out
Motivation: we want to have links for all constants in the API documentation, even if they are behind notation.  See companion PR leanprover-community/doc-gen#3.
This PR adds the option `pp.links` which, if set to true, annotates things like `ℤ` and `+` and the `fst` in `p.fst` with the corresponding constant names (i.e., `int`, `has_add.add`, and `prod.fst`).  The markup syntax for this annotation is as follows:
`<U+E000>prod.fst<U+E001>fst<U+E002>`
The Unicode code points `U+E000`, `U+E001`, `U+E002` are taken from the Private Use Area.  Hopefully nobody uses them for anything else.
=> Annotate pretty-printed output with full constant names

src/library/vm/init_module.cpp, src/library/vm/vm_float.cpp, src/library/vm/vm_float.h
Fix the finalization order of the `vm_float` module and rename `mk_vm_float` to `to_obj` according to the naming convention.
=> VM float cleanup

src/frontends/lean/builtin_cmds.cpp, tests/lean/run_cmd_type.lean, tests/lean/run_cmd_type.lean.expected.out
Fixes #101. Internally, `run_cmd foo` expands to something like `((by (foo >> tactic.try tactic.triv)): true)` but in a different way than it would interactively, so the term passed to `by` can end up having type `lean.parser unit` since there is a coercion from `tactic` to `lean.parser`:
```lean
#check (foo >> tactic.try tactic.triv)
-- foo >> ↑(tactic.try tactic.triv) : lean.parser unit
```
This change forces it to have type `tactic unit`.
=> fix(builtin_cmds): force tactic type in run_cmd

src/library/type_context.cpp, tests/lean/run/mvar_beta_isdefeq.lean
Currently, `quick_is_def_eq` incorrectly returns false (i.e., not defeq) for these expressions.
=> fix(library/type_context): `?m_1` and `(λ x, ?m_1) y` are definitionally equal

library/init/meta/expr.lean, library/init/meta/tactic.lean, src/frontends/lean/scanner.cpp, src/frontends/lean/scanner.h, tests/lean/run/comment.lean
This allows nested comment blocks to be placed in docstrings and module docs. This will make it possible to write comments in Lean code examples in docstrings.
See https://github.com/leanprover-community/mathlib/pull/1963#issuecomment-585889606 and https://leanprover-community.github.io/archive/113488general/42453nestedcommentblocks.html
Question: if we want to merge this, where should it be documented?
=> feat(scanner): allow nested comment blocks in docstrings

library/init/meta/interactive.lean, library/init/meta/simp_tactic.lean, library/init/meta/well_founded_tactics.lean, src/library/inductive_compiler/nested.cpp, src/library/tactic/eqn_lemmas.cpp, src/library/tactic/simp_lemmas.cpp, src/library/tactic/simp_lemmas.h, src/library/tactic/simplify.cpp, tests/lean/run/pathsimp.lean, tests/lean/simp_symm.lean, tests/lean/simp_symm.lean.expected.out
Allow the `simp` tactic to apply reverse direction, analogously to `rw`: if `h : a = b`, then `simp [<-h]` will replace all instances of `b` in the goal with `a`.
This implementation is inspired by `rewrite`: we store a flag for each `expr` lemma passed to `simp`, indicating whether to reverse it. When all parameters to the lemma have been instantiated (so that the lemma has the form `h _ ... _ : R _ _`, `mk_symm` is applied to it to get the reverse relation.
=> feat(library/init/meta/simp_tactic) `simp` with reversed lemmas

.travis.yml
This should hopefully fix the ccache errors (by simply removing the ccache support).
=> chore(travis.yml): simplify travis config

library/init/core.lean
Currently we have both `has_insert.insert` and `insert`, which do exactly the same thing.  This causes a bit of headache since built-in set notation uses `has_insert.insert` but you typically write `insert`.  We have a simp lemma in mathlib that replaces `has_insert.insert` by `insert`, but then you can't use built-in set notation such as `{a}` in simp lemmas...
=> refactor(library/init/core): replace insert definition by export

library/init/meta/interactive.lean, library/init/meta/tactic.lean, tests/lean/by_contradiction.lean.expected.out
The docstrings for by_cases, by_contra, by_contradiction had
`local attribute classical.prop_decidable [instance]`
instead of
`local attribute [instance] classical.prop_decidable`.
=> fix(init/meta/interactive,tactic): docstring fix

doc/changes.md
I was a bit negligent and didn't require changelog entries for the PRs, so I've collected them myself.
=> doc(doc/changes): changelog for 3.6

leanpkg/leanpkg/lean_version.lean, leanpkg/leanpkg/main.lean
This PR contains the first option as discussed in #126.
=> fix(leanpkg): Correctly reference the community fork of lean in leanpkg.toml

extras/latex/lstlean.md, extras/latex/lstlean.tex, extras/latex/sample.tex
- Make more symbols `symbolcolor`
- Highlight strings. Add `errorcolor` and `stringcolor`.
- Add a few more symbols used in mathlib
- Add package to `sample.tex` which was required by previous commits.
=> feat(lstlean.tex): updates

library/init/meta/congr_tactic.lean, src/library/congr_lemma.cpp, tests/lean/simp_subsingleton.lean, tests/lean/simp_subsingleton.lean.expected.out
The `simp` tactic uses `mk_congr_simp` to find rewritable subterms. If a subterm has a type which is an instance of `subsingleton`, then `mk_congr_simp` did not include this in the rewritable subterms (i.e. those with `congr_arg_kind::Eq`). This results in `simp` failing on goals of the form `(x : some_subsingleton) = (y : some_subsingleton)`. This is rather counterintuitive, especially since `rewrite` has no problems with such goals.
This PR tries to solve this issue by allowing subsingleton terms to have `congr_arg_kind::Eq` if that gives no conflict, i.e. no subterms with `congr_arg_kind::Eq` that have a dependency on the subsingleton term or vice versa. As a result, whether `simp` can rewrite a term should not depend (too much) on whether there is a `subsingleton` instance floating …
=> fix(src/library): allow `simp` to rewrite subsingletons

src/api/module.cpp, src/library/module.cpp, src/library/module.h, src/library/module_mgr.cpp, src/library/module_mgr.h, src/shell/CMakeLists.txt, src/shell/server.cpp, src/shell/server.h, src/util/CMakeLists.txt, src/util/hash.cpp, src/util/hash.h, src/util/line_endings.cpp, src/util/line_endings.h, src/util/path.cpp, src/util/path.h, tests/lean/importing/test_importing.sh
This should resolve the timestamp problem (#112) -- with this change, timestamps are irrelevant and Lean only recompiles .oleans if the source code has changed. This PR replaces `m_mtime` and `m_trans_mtime` in the module manager with `m_src_hash` and `m_trans_hash` which are stored in .olean files and defined as follows:
```cpp
// Hash of the Lean source (after normalizing line endings) yielding this module:
// - if m_source == LEAN, hash(remove_cr(m_contents))
// - if m_source == OLEAN, value loaded from the .olean
unsigned m_src_hash;
// Transitive hash of all source code this module was built from,
// i.e. m_src_hash mixed with the m_trans_hash of each imported module
unsigned m_trans_hash;
```
If `foo.lean` changes, the `m_src_hash` in `foo.olean` no longer matches while if any of …
=> feat(module): hash source code instead of tracking timestamps

src/library/type_context.cpp, tests/lean/run/slow_tc_synth.lean
As posted on Zulip, the following instance causes massive performance problems:
```lean
instance topological_ring.to_topological_add_group :
∀ (α : Type u) [_inst_1 : topological_space α] [_inst_2 : ring α]
[t : topological_ring α],
topological_add_group α
```
(Note that `topological_ring` has instance-implicit arguments for `topological_space` and `ring`; similarly, `topological_add_group` has instance-implicit arguments for `topological_space` and `add_group`.)
If `α` is not a topological ring, then this instance will cause a massive search.  First, we enumerate all instances for `topological_space`, and then all instances for `ring`.
However, none of this is necessary since these instances are already contained as subterms in `topological_add_group` (and we have to pick them one way or …
=> perf(library/type_context): speed up topological_ring.to_topological_add_group

src/library/type_context.cpp, tests/lean/defeq_match.lean, tests/lean/match_at_type.lean, tests/lean/run/sigma_match.lean
The issue was that `nat.add` didn't get unified with `λ a b, nat.add a b`, because `nat.add` is defined using matches. If such a definition is applied to a term, only when the term matches one of the match cases the whole is unfolded.  In contrast, if there is no application, the constant `nat.add` is happily unfolded all the way. Thus the elaborator decides unification fails.
There are basically two solutions: unfolding more (i.e. also unfold `nat.add a b`) or unfolding less (i.e. don't unfold `nat.add`). Since unfolding `nat.add` would expose implementation details, namely the `nat.add._main` function, choosing to unfold less is better.
But this leads to another issue: now `λ <a, b>, a` does not unify with `λ <a, b>, a` if they are defined separately. This is not a big issue since …
=> fix(library/type_context): inconsistent unification of match-based definitions

src/library/tactic/vm_type_context.cpp, src/library/vm/interaction_state.h, src/library/vm/interaction_state_imp.h, tests/lean/issue136.lean, tests/lean/issue136.lean.expected.out
Fixes #136.
The interaction_monad.exception constructor takes an `option (thunk format)` as argument.  The functions in `interaction_state_imp.h` treated this inconsistently: `get_exception_message` returned the option, while the `mk_exception` function wrapped it in a some.
=> fix(library/vm/interaction_state_imp): remove dangerous functions

doc/changes.md, src/CMakeLists.txt, src/library/module.cpp, src/library/module.h, src/library/module_mgr.cpp, src/util/optional.h
No longer requires .lean sources to exist to load the .oleans, so that binary distributions are possible, e.g. in the Lean web editor. Issue noted in [Zulip](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/Lean.203.2E7.2E0.20released!/near/190659957). CC @bryangingechen
=> fix(module): load standalone .oleans

doc/changes.md, src/CMakeLists.txt, src/library/module.cpp
This wasn't caught by the [importing test](https://github.com/leanprover-community/lean/blob/master/tests/lean/importing/test_importing.sh) because it only fails for a small percentage of .oleans which happen to contain something like `\r\n` in the header.
=> fix(module): open .oleans in binary mode on Windows

library/init/logic.lean, tests/lean/simp_ite.lean
This PR is based on discussion on [mathlib PR #2223](https://github.com/leanprover-community/mathlib/pull/2223).
The lemma `if_simp_congr` removed in this PR caused `simp` to always use `decidable_of_decidable_iff` to construct a `decidable` instance for the condition of an `if` expression. That meant that `if c then t else e = if c' then t else e` often did not get solved by `simp`, getting stuck on `dec_c = decidable_of_decidable_of_iff ...`. There is another `congr` lemma, `if_congr`, defined just before `if_simp_congr`, which does allow the `decidable` instances to differ. Because of the order of the declarations, `if_simp_congr` takes priority.
It seems that `if_simp_congr` was introduced to allow progress rewriting `if c then t else e` to `if c' then t else e` without requiring a …
=> fix(library/init): remove `if_simp_congr` for more powerful `if` simplification

library/init/meta/simp_tactic.lean
See discussion at https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/unbearable.20unhappiness.20of.20.60simp.60.20not.20working
=> fix(meta/simp_tactic): call instantiate_mvars on target before simplifying

library/init/algebra/field.lean, library/init/algebra/ordered_field.lean, library/init/algebra/ordered_ring.lean, library/init/data/prod.lean, library/init/function.lean, library/init/logic.lean
refs #160
* `inv_inv'` takes `a` as an explicit argument;
* `div_mul_left` for `division_ring`s;
* `prod.map` and `function.uncurry` don't use pattern matching;
* export `inhabited.default` instead of `def`ining it
* remove unneeded `fun.inhabited`.
the issue.
=> chore(library/init/*): a few small improvements

library/init/core.lean, tests/lean/pp_zero_bug.lean.expected.out, tests/lean/run/1562.lean
See discussion at https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/unbearable.20unhappiness.20of.20.60simp.60.20not.20working
Search for `has_zero.zero _` and remove the underscore in a few places! (Being careful not to change `@has_zero.zero _`.)
We'll also be able to reverse the clunky changes from #2290! (I checked that the `example`s I added to verify correct behaviour in that PR still work when you remove the `reducible` attributes on the `has_coe_to_sort`s.)
=> fix(init/core): make type argument in has_one/has_zero implicit

library/init/algebra/functions.lean, library/init/algebra/ordered_group.lean, library/init/algebra/ordered_ring.lean, library/init/data/int/order.lean, library/init/data/nat/lemmas.lean
This PR renames ordered groups and monoids to make name space for their multiplicative counterparts.
=> refactor(algebra/*): rename ordered groups/monoids to ordered add_ groups/monoids

library/init/meta/float.lean, src/library/vm/vm_float.cpp, tests/lean/float.lean, tests/lean/float.lean.expected.out
I was doing some coding with floats and I realised that we don't have a way of parsing floats from strings or casting floats to integers. 
This PR adds 
- `native.float.of_string : string -> option float`, which under the hood uses `std::stof`
- `native.float.ceil`, `floor`, `round` and `trunc` now have `int` as their return type instead of float. 
Since the float feature is quite new and ints coerce to floats I think that it is unlikely that changing `floor : float -> float` to `float -> int` is going to significantly break any dependent code and it seems less cluttered to simply change the type signature rather than make a whole new set of constants for the integer versions.
=> feat(native.float): add `float.of_string` and change `ceil`, `floor`, `round`, `trunc` to return ints

library/init/algebra/group.lean
This is necessary for `to_additive` to work.
=> fix(init/algebra/group): use same definition for add_comm_monoid and comm_monoid

library/init/algebra/field.lean, library/init/algebra/group.lean, library/init/algebra/ordered_field.lean, library/init/algebra/ring.lean, library/init/data/int/basic.lean, library/init/data/int/order.lean, library/init/data/nat/lemmas.lean, tests/lean/1952.lean.expected.out
This causes way too many issues in mathlib.  In order to revive this, please port mathlib first.  I'm happy to do a special "remove axioms"-release once we have a branch of mathlib that works with this change.
Non-exhaustive list of things that break:
- For example a group with zero now has more axioms than a division ring.  So you cannot construct a gwz instance from a dr instance, but you need to write an extra `..(by apply_instance : semiring α)`.
- Unification failures in `dfinsupp`.  (This is the part where I'm giving up.)  Since `add_group` no longer extends `add_monoid`, the unifier cannot compute the `add_monoid` instance.  This is really ugly, because addition requires `add_monoid`.  Hence lemmas such as `add_apply` just don't work anymore.
=> chore(*): revert removal of unnecessary axioms

doc/changes.md, library/init/meta/expr.lean, src/library/vm/vm_expr.cpp
The `prod.has_reflect` instance uses the `reflect.subst` function four times.  This function is inlined (because it must be inlined to forget the unused argument), and the match is expanded into an expression recursor.  The resulting term and VM program is huge, causing significant slowdown in tactic parsing.
This PR speeds up the `foo` tactic by a factor of 5: https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/set.20is.20slow/near/193433744
=> refactor(init/meta/expr): better corner-case for expr.subst

library/init/data/array/basic.lean
`array.map` was 50x slower than a naive implementation using `d_array.mk`.  Now it is twice as fast as the naive implementation.
```lean
import data.buffer
universes u v
def array.mmap_core {m n} {α β : Type u} [monad m] (as : array n α) (f : α → m β) : ∀ i ≤ n, m (array i β)
| 0 _ := pure array.nil
| (i+1) h := do
bs ← array.mmap_core i (le_of_lt h),
b ← f (as.read ⟨i, h⟩),
pure $ bs.push_back b
def array.mmap {m n α β} [monad m] (as : array n α) (f : α → m β) : m (array n β) :=
as.mmap_core f _ (le_refl _)
def d_array.map' {n : ℕ} {α : fin n → Type u} {β : fin n → Type v} (f : Π (i : fin n), α i → β i) (x : d_array n α) :
d_array n β :=
d_array.mk $ λ i, f i $ x.read i
def array.map' {n : ℕ} {α : Type u} {β : Type v} (f : α → β) (x : array n α) :
array n β :=
x.map' $ λ _, f
def …
```
=> perf(library/init/data/array/basic): speed up array.map

src/frontends/lean/dependencies.cpp, src/frontends/lean/parser.cpp, src/frontends/lean/parser.h, tests/lean/run/import_open_locale1.lean, tests/lean/run/import_open_locale2.lean
This PR changes the parser to parse the imports indentation-sensitively, like some things in Lean 4:
```lean
import foo
bar
open_locale classical -- runs user command
```
and
```lean
import foo
bar
open_locale classical -- imports open_locale and classical modules
```
The unexpectedly hard part about the implementation is that the `open_locale` token is parsed differently after importing the dependencies.  Before it is an identifier, afterwards it is a command keyword.  Hence we do not consume the final token in the `parse_imports` function and let the `process_imports` function do this after importing the dependencies.
=> feat(frontends/lean/parser): support user commands after imports

doc/fixing_tests.md, src/frontends/lean/decl_util.cpp, src/frontends/lean/util.cpp, src/frontends/lean/util.h, tests/lean/run/univ_of_instances.lean
Fixes #146.
This fixes a headache that arises throughout mathlib's category theory library.
=> fix(frontends/lean/decl_util): collect univ params of implicit instances

src/frontends/lean/scanner.cpp, tests/lean/run/doc_string6.lean
This PR fixes a bug in #113 that mangled `/-` and `-/` in nested doc strings. 
Fixes https://github.com/leanprover-community/doc-gen/issues/17.
=> fix(scanner): read nested doc strings properly

library/init/meta/interactive.lean, tests/lean/simp_symm.lean
This fixes issue #193.
The code to erase a lemma `h` from the simp set for calls of the form
`simp [←h]` matched on `h = expr.const _ _`. It should also match when `h` is a
`local_const`. I think this issue was not caught by the test because the the
arguments to `simp` were quoted incorrectly, so I've changed the test to use
the tactic quoter instead.
=> fix(library/init/meta/interactive): removing for `simp [← local_const ...]`

src/frontends/lean/tactic_notation.cpp
In tactic mode, `calc` was an abbreviation for `exact calc`, and I propose we change it to `refine calc`.
the issue.
=> change interactive calc to `refine calc`

src/library/module_mgr.cpp, src/library/module_mgr.h, src/shell/lean.cpp, src/shell/server.cpp, src/shell/server.h
Add an option to Lean that uses old oleans instead of rebuilding them.  That is, use oleans whenever available, no matter whether they are out-of-date or not.
Usage: `lean --old ...`
See also https://github.com/leanprover/vscode-lean/issues/151#issuecomment-600257372
=> feat(library/module_mgr): add flag to use out-of-date oleans

src/frontends/lean/parser_config.cpp, tests/lean/notation_pp_priority.lean, tests/lean/notation_pp_priority.lean.expected.out
If you have a notation for a special case, e.g. `finset.sum finset.univ`, and a notation for a general case, e.g. `finset.sum`, you can now give the special-cased notation a higher priority to ensure it is used by the pretty-printer when applicable.
When deciding how to pretty-print an expression, Lean looks up the notations associated to the head of the expression. It tries them one-by-one until it finds a notation that matches the expression. The order in which they are tried used to be the definition order. This PR changes this ordering to have higher-priority notations first.
Although `notation_entry.priority()` is also used by the parser, it doesn't seem to be set at all in mathlib. I expect that there will be no conflicts between the usage of `priority` in the parser and in the …
=> feat(src/frontends): order notation by priority in pretty-printer

src/library/fun_info.cpp, tests/lean/run/sebastien_coe_simp.lean
The default congruence lemma generated for `coe_fn` is specialized only for the first argument, ignoring the type-class instance for the function coercion.  The congruence lemma hence needs to assume that the coercion is dependent and that the result type is not necessarily a function type.  That is, using the congruence lemma you can neither rewrite the coercee (because the return type depends on it) nor the argument (because the "function coercion" could return a non-function :shrug:).
By specializing to two arguments, we can generate much better congruence lemmas for non-dependent function coercions.  In particular, for a non-dependent coercion to a non-dependent function the resulting congruence lemma can rewrite both the coercee as well as the argument.
We implement this by adding an …
=> feat(library/fun_info): improve congruence lemmas for coe_fn

library/init/data/list/basic.lean, library/init/meta/interactive.lean, library/init/meta/tactic.lean, tests/lean/1513.lean.expected.out, tests/lean/rename.lean, tests/lean/rename.lean.expected.out
This PR ports the `rename` interactive tactic from mathlib (with some additional improvements). Features over current core `rename`:
- Multiple hypotheses can be renamed at once.
- The order of hypotheses doesn't change.
- If there are multiple hypotheses with the same name in the context, they are all renamed.
Breakage in `mathlib`:
- Remove `rename` and `list.after` (now in core).
- Fix one proof that relies on edge case behaviour of old `rename` when there are multiple hypotheses with the same name.
=> feat(library/init/meta/*): port `rename` tactic from mathlib

library/init/meta/interactive.lean
Fix an error in the code sample. Also add a note about how renaming
works when there are shadowed hypotheses.
=> doc(library/init/meta/interactive): fix docstring of tactic.interactive.rename

src/library/tactic/rewrite_tactic.cpp, src/library/type_context.cpp, src/library/type_context.h, tests/lean/1277.lean.expected.out, tests/lean/run/mario_type_context.lean
Fix copied from https://github.com/kha/lean4/commit/f8cedb33e70c9d90c9d81a542340bba0b504f8e6.
See discussion: https://leanprover.zulipchat.com/#narrow/stream/116395-maths/topic/witt.20vectors/near/169124238
=> fix(library/type_context): do not unfold irreducible definitions when trying to unify/match types

src/library/tactic/rewrite_tactic.cpp, tests/lean/run/rw_instantiate_mvars.lean
`rw` will sometimes fail to notice an equality if the type of the input theorem is an instantiated metavariable. This does the `instantiate_mvars` call first, before any of the pi-matching or other things that could be affected later in the procedure.
=> fix(library/tactic/rewrite_tactic): instantiate mvars in rw

src/frontends/lean/parser.cpp, src/library/abstract_parser.h, src/library/ast_exporter.cpp, src/library/module_mgr.h, src/library/tactic/tactic_log.cpp, src/library/tactic/tactic_log.h, src/shell/lean.cpp
=> feat: export pretty-printed tactic states

src/shell/CMakeLists.txt
Combined with https://github.com/leanprover/lean-client-js/pull/58, this seems sufficient to fix the web editor.
Strictly only `ERRNO_CODES` seems necessary, but the code certainly expects `PATH` too.
=> fix: Add missing emscripten export
