leanprover-community/lean

- src/library/vm/vm_io.cpp
- tests/lean/run/1010.lean
get_cwd used to crash every time. Fixed.
> fix(vm/get_cwd): add test for get_cwd

- library/system/io.lean
- library/system/io_interface.lean
- src/library/vm/vm_io.cpp
Add `meta def serialize : handle → expr → io unit` and `meta def deserialize : handle → io expr` with the expected semantics.
> feat(io/serial): add `expr` serialization/deserialization functions

- library/init/algebra/field.lean
Make Kenny's fix to core lean (eliminating a repeated instance).
> fix(init/algebra/field): repeated instance

- src/library/tactic/revert_tactic.cpp
- tests/lean/revert_err.lean
- tests/lean/revert_err.lean.expected.out
> fix(tactic/revert_lst): check that the provided expressions are variables

- library/data/buffer/parser.lean
> fix(doc): spelling

- .gitignore
- .travis.yml
- library/init/meta/environment.lean
- library/init/meta/expr.lean
- library/init/meta/tactic.lean
- src/frontends/lean/decl_cmds.cpp
- src/frontends/lean/decl_util.cpp
- src/frontends/lean/decl_util.h
- src/frontends/lean/definition_cmds.cpp
- src/frontends/lean/definition_cmds.h
- src/frontends/lean/elaborator.cpp
- src/frontends/lean/parser.cpp
- src/frontends/lean/parser.h
- src/frontends/lean/util.cpp
- src/frontends/lean/util.h
- src/library/equations_compiler/structural_rec.cpp
- src/library/io_state.cpp
- src/library/io_state.h
- tests/lean/add_defn_eqns.lean
- tests/lean/add_defn_eqns.lean.expected.out
> add a Lean function to access the equation compiler

- src/library/tactic/revert_tactic.cpp
- tests/lean/revert_err.lean
- tests/lean/revert_err.lean.expected.out
> fix(tactic/revert_tactic): disallow duplicates

- src/CMakeLists.txt
- src/kernel/expr_maps.h
- src/library/arith_instance.h
- src/util/log_tree.cpp
- src/util/numerics/double.cpp
- src/util/numerics/float.cpp
- src/util/numerics/numeric_traits.cpp
- src/util/task_builder.h
- src/util/thread.h
> Fix building with GCC 9.1.0

- src/CMakeLists.txt
> chore(build): Fix Fedora build

- src/library/tactic/change_tactic.cpp
- tests/lean/change_tac.lean
- tests/lean/change_tac.lean.expected.out
> feat(tactic/change): allow `change` to be used to rename bound variables

- leanpkg/leanpkg/main.lean
This is one possible way to address #105 . 
the issue.
> feat(leanpkg): avoid version warning for external Leans

- README.md
> doc(readme): clarify relation to 3.4.2 and 4

- extras/latex/lstlean.tex
The old one is very out of date. This is the version I used for the last Lean paper I wrote. There are probably more updates to be made, feel free to add to them.
the issue.
> feat(extras): update lstlean.tex to be more modern

- library/init/algebra/functions.lean
- library/init/algebra/group.lean
- library/init/algebra/norm_num.lean
- library/init/algebra/ring.lean
- library/init/data/int/basic.lean
- library/init/data/int/order.lean
> feat(init/algebra/group): remove simp attribute from sub_eq_add_neg

- .appveyor.yml
- .travis.yml
- packages/.gitignore
- packages/leanpkg.toml
We are moving fast and breaking stuff.
> chore(.travis.yml): do not build mini_crush, etc.

- src/library/tactic/simplify.cpp
- tests/lean/run/simp_tc_err.lean
Fixes https://github.com/leanprover-community/lean/issues/137
> fix(library/tactic/simplify): catch exceptions

- .travis.yml
- library/init/meta/derive.lean
- library/init/meta/environment.lean
- library/init/meta/tactic.lean
- script/travis_long.sh
- src/library/vm/vm_environment.cpp
> feat(tactic/mk_protected): make `protected` part of the API and use it in `derive`

- library/init/category/monad_fail.lean
- library/init/category/reader.lean
- library/init/coe.lean
- src/library/type_context.cpp
- tests/lean/run/tc_right_to_left.lean
> perf(library/type_context): process instance arguments from right to left

- library/init/category/lift.lean
I missed these instances in #139
> fix(library/init/category/lift): flip instance arguments

- src/frontends/lean/calc.cpp
- src/frontends/lean/interactive.cpp
- src/frontends/lean/local_decls.h
- src/frontends/lean/local_level_decls.h
- src/frontends/lean/parser.cpp
- src/frontends/lean/pp.cpp
- src/frontends/lean/print_cmd.cpp
- src/frontends/lean/tactic_notation.cpp
- src/library/inductive_compiler/util.cpp
- src/library/library_task_builder.cpp
- src/library/module.cpp
- src/library/module_mgr.cpp
- src/library/tactic/smt/theory_ac.h
- src/library/vm/vm.h
- src/library/vm/vm_io.cpp
- src/shell/server.cpp
- src/util/json.hpp
- src/util/sexpr/format.h
- src/util/task_builder.h
> chore(*): fix compiler warnings

- README.md
Other suggestions for improving the documentation welcome.
> doc(readme): clarify community version

- src/library/app_builder.cpp
fixes an issue reported on Zulip https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/app.20builder.20exception.2C.20caused.20by.20.60subst.60/near/192116230
> fix(library/app_builder): whnf universe first

- doc/changes.md
> doc(*): update changelog for 3.8

- src/library/tactic/simp_lemmas.cpp
- tests/lean/run/simp_emeta_order.lean
> fix(library/tactic/simp_lemmas): reverse order of emetas

- src/library/compiler/erase_irrelevant.cpp
- src/library/compiler/vm_compiler.cpp
- src/library/string.cpp
- src/library/string.h
- src/library/vm/optimize.cpp
- src/library/vm/vm.cpp
- src/library/vm/vm.h
> feat(library/vm): string literals

- src/library/compiler/preprocess.cpp
Inlining seems to expand string macros sometime, let's fold them into macros again.
> fix(library/compiler): convert string expressions into macros

- library/init/meta/interaction_monad.lean
- library/init/meta/lean/parser.lean
- src/frontends/lean/parser.cpp
- src/frontends/lean/parser.h
- src/frontends/lean/user_notation.cpp
- src/library/vm/vm_parser.cpp
- tests/lean/list_local_vars.lean
- tests/lean/list_local_vars.lean.expected.out
- tests/lean/user_notation.lean
- tests/lean/user_notation.lean.expected.out
and access to included variables
the issue.
> feat(parser/add_local): add control for local scope, pattern parsing

- library/data/buffer.lean
- library/init/data/array/basic.lean
- src/library/vm/vm_array.cpp
- tests/lean/run/array1.lean
- tests/lean/run/array2.lean
> feat(data/*): mmap and map for d_array, array, and buffer

- src/frontends/lean/elaborator.cpp
- tests/lean/123-1.lean
- tests/lean/123-1.lean.expected.out
- tests/lean/123-2.lean
- tests/lean/123-2.lean.expected.out
> hack(frontends/lean/elaborator): remove assertion

- doc/changes.md
Feel free to edit if I got anything wrong!
> doc(*): update changelog for 3.9
